travis:
  secure:
    BINSTAR_TOKEN: AE/T9FViyY2mOcUDje2WKpmhS/a9Gh8z+bRIJZ5I/TBkQrfHdT0jc810kbX7A47C/uwZujJOW14gWfVjrbFmDlaacKu4lmh1gj7AqfjRXsr2aoMDY+NpkhFhNkEuZ7d7WlGY6A8e9NAohsgUQkia8uvPWGWoghEQwF02DFSfzCYBLm+3G3JDKAriV6/1XjxAin6/H9Sp1uQxkg5A/JUmLfVdFRHxO5fSf/Pgno6t0aSfBefT2Fu9DRQWbz+06J9S0YfIrP8CMV+WvdF16Zyh40C8qzFvRRpJIC5Mvs0Yeai+8vOcboS+DS//SZVPtLZXoXF65x/5srHXxX1wqUXLnlENCSsEJpOgV8we5VCIgAX0MJAkb2+J5drj4Es+4mydkKDhdNSt/A6875MnzH/HricJBRY8ectGDZ5UHL2cip8sauY1Kp8ui5lNokVK0a8IhK7NnKbzrI5vQSduImCdOFYwyOKa87QSKeRgs9OmhNa9i12aQ+XcoASPn+ppzjt6USN7XdlZjhLs0UB8BqJXhHwFQ1UIXaKVEiIZM98MsmjyXBgzLavktN//HrNgl9YM8rL3f2v/6kNzFCvYO7LNudWkVSnXysEGh4c0YlYOx8ejHQvjL2EKf/wzHHU4ZqLEkfEa22nJRmW1YMlpftTBreyaUTIG7WcpjYG0d36aE6w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
