travis:
  secure:
    BINSTAR_TOKEN: ew7afliwMdH6yAKhBDCmbU8aepqKgEoTZ5F1T0YT2f2b9pBRlOFdLfASEQge7h0yLrVXS0bEFs8M7OqnRCN+TltA+e2uj72Yym7F54dUpfSt9lu8Ac8ivlRV+izh50ub9+PlAvLktksigm6LBGhfioVVhp0ys9+Ypamq5mo+dCQIrgDRhWMV5+ubps5ILHRi5INWDIgYFL74/ljbL5oiEX+5afkEqEYRwi6hl5F9w0D3jZSa3ZOPBZu7rgEjy6VHFGNJwkfyiqoBajjT1oFCOPorECN5bO//46udBgZyh7Xz5evvbi/apCZF05TRZT0Zl7UePItbBofLviWtJxa87kp+/OazsyGLNjpjaPCg1u0wxL/A0EU9zmR4wLkoA+2AOS3sIlFWZV4ac+AgD+pAFAd4doTddMhzhRrl1+9y2wVR9KcTqhu1ZKj0LjMy5XHak9bub0Roi+B+vZyHlT6wh9fvmAXgrvLk+bXvULun/voE1hSN/YixB9Mv3XPknhZkLKZjrmEa2FQiMlmWKvMoSqq9zeUhlNP10AgoNJG46k9K52+jCBGNyaMRYlbgZ1w12+sVfOW4s8oifPUFCTHlt6AYnQTpq+1Ue6YIk2hxuoUv2mCBA2Q/HxRPXwvzaR98dwggQN5FMz2iDvFq0NKM5J+neAqxdjdJkTwkkT7WyUU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
