travis:
  secure:
    BINSTAR_TOKEN: iW0LBYnG+nJbRMka0iCwV1BZq0PBXd35hA+plCrc+SiVWDHJ7MdChel90BVObvIar8vLe6AykEWWnSEYuxZYfw5ytNa62qQXZvrI2byg/dLEl6zU7huEK9B3ZrDj20ob75fZd3qBajO1wZyZCeeB/Z67qBwedeH389COcAIvLgtYAL/Qth947PhE5qpP1gVLncjIYxgQtBwz4Dm5jI1CBquNM+Q4P79tLane1UglFgyAss8IPZsnzE5lR6brr22Ev8dHmF1Q/OESc6jASbARHsvXgsoCld8ouTF7Twb2n6dW/1MI/QEUR/sIXrmzAQbvgaGZgIIzNPBRKUvmNP7Vpnmb2QpaY91Dm2Juz+rNmz85RCz3D1KvAEb2oRvGgmfyP3Q/Uyov2wtlLlGYYX6OUVv6M8FefO7Wa4jTUM5OR9QI/ZQ9/snIbNodAIKP/D35re7L2ltC7ZtwJ2OHh2tDAaN/8bT+zWSa81EN1n/TKFZwisRMQ26IRhSrB8lYRe5l4JJRbdZHN+yYlAOB9gfRf6JoCgn66alQCR9cB19N/zbddQZZg64BcnWmXtiiMzqdtPpPGtwTykqmLNPpVWBnm5ZIb+INZ9FAQ1P0QSXZqqsuSXU1rAKLPkJuNkg8z20l1ubfGwQ4Rd7KSsIgEjo9c+2eAMsXMe1rOxaA3rQP7EM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
