appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: S4OtSzNIdDANMh3tvndWYearisxFSR4PzRO12WT1jcN05mZnoER+1gUhkaVoulMxqoTMVEhyPNsPFdftFrBkx6dHUuWSQX7nZbOxcAIop9DbtgrRFtZE/JnyfzvqfYQSLe1xJn26Ef+emdYKpUSIvJrpGP8Q+CaA8pBfG1UkWuUOSoicLUTfmY7ZMoxEUvf7BTxTJhPyjPt8H21A7u/GH9Upmr/Cp+eL2YCGZSwOx3+EuolB/JzoAMPwFzsqnTnpYLhDknoIG8c0YdOl8bS44IXqzA1WXIsAIMRtJz+pakVVBcj54kUC1WmmS+gdLeySV7Yylw/JJcIkNJieFgWMVmEVio6nPoqdpgITcM9fZ0UAxsvgu5N/7sKkqhH4mEM5KEys3X/P9Ta9fuiwpqmtEnmpEGFhucMnlKuVP4Dy9+z9gl6yZnl7lNdAQMdEAFUJ7QwTvQsJBhAp6qmXWKlpGjIXLDz2JeQyUVz9Yd5yDemxTTqE7WZDO3Ztma9JkSaIFGlwUOSM6wH/0p6iqB7IAPWj9V4QvNJg0NJKjXDIJj9LTHOY+JTqKfk83WCNjZ359IwapiLFoAZ5DERy1m52VTzOH+hQa3hBry63OHioUbEEzpD1dIhCWvI0Y63ieZo4z6XcMnbFZPQdwR3Sjh2X0iMrjdppl3x+I+lmGK3nohw=}
conda_forge_output_validation: false
