travis:
  secure:
    BINSTAR_TOKEN: st+2AbByfIS6AjGMdR+VI5K/UGZqNAZLFM3XkFrJ1KPKpIiX0UDfLqWDGuS+FuF2aJnEwUhFT1N99Yz6kePM4v3QamSSFLk/azWyWdazmz1sh9Gc0NZR6aVJ+FzgdJB2gtdYaYaN+AS9s+zX5PZ5l+HJ25YT7tgHvCU0eYGZvqNhKrNMlptM8ZNfq4A7r7Ovi3ROQ30YmqcoRZ+TFldl5ZEpr4d8HNdjoZ4HHKV8YkMKv1x6K7BQFitGCBabzxx4fkxaPyrFgjyNJl3bAQDI75a5i7cgkP7DqbxVYqMlx/zskudIxZ+Ei+plioU50U/snD0dh02nm2+NpcKerLqB3cTcjzOFaJxiVw5ZtYPblEwIl/ngqtpzhM+sRRh/rrIw2lHxU8PtUDHBoOOI0lPZqevvxRITwv+F/iTQOfwBDGxe4jRgAPrL7Dcje1OYXxZAG4MRN/YidXB9/N+XgI5CQwgH/2+EF2TSzeFgfmWzrdzRQi/WGLkBevccOOGGsc2ZsLCzGDwsEl/x2dpZht1kI220JTRFNgE4EhQ0yrqfmC9VWOpJ3qHxGBwPZZrMx0+9R9hStsZrGkb7hAmJENC+2Mu6U/Jqq7TU2++QG6kD/8q0SnTcPitGSxh2BuWvn+3hPLetoc2LA2hNp+8SCDAly0UG9e+PFmGh3nitH4btIns=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
